"""empty message

Revision ID: 21edf029ee90
Revises: 0fde3cf92ada
Create Date: 2024-03-19 16:24:35.511906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21edf029ee90'
down_revision = '0fde3cf92ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
