"""empty message

Revision ID: 76a731fc681b
Revises: d4543e0b6348
Create Date: 2024-03-22 00:36:44.047566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a731fc681b'
down_revision = 'd4543e0b6348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.String(), nullable=True))

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###
