"""empty message

Revision ID: d4543e0b6348
Revises: 6cb103f1845e
Create Date: 2024-03-20 18:01:07.602264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4543e0b6348'
down_revision = '6cb103f1845e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'type', ['type_id'], ['id'])
        batch_op.drop_column('type.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type.id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
